software:
  version: "0.0.2"
  app_name: gpse
  author: "XIAOLIU, JZHANG"
  email: "1468835852@qq.com, zhangjian199567@outlook.com"
  url: https://github.com/xsx123123/GPSE
  description: "Genomic Prediction with Stacking Ensemble for horticultural crops"


logs:
  log_level: INFO
  more_info: false
  Label: gpse


